### ISSUE TITLE
invoice-ninja

### ISSUE THREAD

**Issue by pierreozoux** [libresh/applications#105]
https://github.com/hillelcoren/invoice-ninja
##

**Comment by almereyda** [comment]
We are looking at Boxbilling. I like it a bit more.

**Comment by pierreozoux** [comment]
I plan to use odoo for IndieHosters, but one user is using invoice-ninja :)
I'm interested for my freelance work.
Thanks for the suggestion.

**Comment by pierreozoux** [comment]
Looks cool the integration with the registrars!

**Comment by almereyda** [comment]
There's a Dockerfile at https://github.com/rollbrettler/Dockerfiles/tree/master/invoice-ninja

But https://invoiceplane.com/ also seems nice.

**Comment by pierreozoux** [comment]
There is this package: https://github.com/lalop/invoice-ninja-docker

**Comment by almereyda** [comment]
... which apparently moved to https://github.com/invoiceninja/dockerfiles

**Comment by pierreozoux** [comment]
we have it also \o/
