### ISSUE TITLE
Backup procedure

### ISSUE THREAD

**Issue by almereyda** [libresh/applications#106]
The backup script provide by most IndieHosters applications focusses on associated databases.
As Docker is being used, file system state is probably simply kept in host mounted volumes.

How would one further prescribe this workflow?
##

**Comment by pierreozoux** [comment]
## Backup Script

Yes, the idea of an IndieHoster application is to have a script that backup not really persistent data (like databases) and then, you would jsut need to tar the current folder, send it somewhere else, untar, and you are up and running again.
Actually about the database backup, it is mostly an extra care in case of database corruption as the database files are already mounted.

## Interoperability

Yes, It would be amazing to be able to be import/export our backups between sandstorm/yunohost/cozy/indiehosters/you. 
Let's contact them?
Actually it might be easy to set this working between yunohost and cozy (though kload). And then, we can use their system. And then we could contact sandstorm?

**Comment by pierreozoux** [comment]
there is a backup script in libresh/borg-[server|client]
