### ISSUE TITLE
HackPad

### ISSUE THREAD

**Issue by pierreozoux** [libresh/applications#109]
Scala
https://github.com/dropbox/hackpad/blob/master/Dockerfile
https://hub.docker.com/search/?q=hackpad&page=1&isAutomated=0&isOfficial=0&starCount=0&pullCount=0
##

**Comment by almereyda** [comment]
We're using https://github.com/TransforMap/hackpad/commits/master , but
beware the third-party commits ;)

**Comment by pierreozoux** [comment]
Thanks:)

What is the difference?

On 14-12-2015 18:38, jon r wrote:
> We're using https://github.com/TransforMap/hackpad/commits/master , but
> beware the third-party commits ;)
> 
> On 14 December 2015 at 11:57, Pierre Ozoux <notifications@github.com> wrote:
> 
>> Scala
>> https://github.com/dropbox/hackpad/blob/master/Dockerfile
>>
>> https://hub.docker.com/search/?q=hackpad&page=1&isAutomated=0&isOfficial=0&starCount=0&pullCount=0
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/indiehosters/applications/issues/109>.
>>
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/indiehosters/applications/issues/109#issuecomment-164521011
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by almereyda** [comment]
Look at the commit history: It basically adds support for X-Forwarded-For
and swaps the theme.

**Comment by pierreozoux** [comment]
Cool, exactly what I would need :)

On 15-12-2015 18:47, jon r wrote:
> Look at the commit history: It basically adds support for X-Forwarded-For
> and swaps the theme.
> 
> On 14 December 2015 at 21:19, Pierre Ozoux <notifications@github.com> wrote:
> 
>> Thanks:)
>>
>> What is the difference?
>>
>> On 14-12-2015 18:38, jon r wrote:
>>> We're using https://github.com/TransforMap/hackpad/commits/master , but
>>> beware the third-party commits ;)
>>>
>>> On 14 December 2015 at 11:57, Pierre Ozoux <notifications@github.com>
>> wrote:
>>>
>>>> Scala
>>>> https://github.com/dropbox/hackpad/blob/master/Dockerfile
>>>>
>>>>
>> https://hub.docker.com/search/?q=hackpad&page=1&isAutomated=0&isOfficial=0&starCount=0&pullCount=0
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/indiehosters/applications/issues/109>.
>>>>
>>>
>>>
>>> ---
>>> Reply to this email directly or view it on GitHub:
>>>
>> https://github.com/indiehosters/applications/issues/109#issuecomment-164521011
>>>
>>
>> --
>> I use PGP to protect our privacy, if you want to know more, you can
>> follow this
>> https://emailselfdefense.fsf.org/en/
>>
>> If you have further questions, please do not hesitate to ask.
>> You can verify my public key here: https://keybase.io/pierreozoux
>>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/indiehosters/applications/issues/109#issuecomment-164547744>
>> .
>>
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/indiehosters/applications/issues/109#issuecomment-164852691
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by pierreozoux** [comment]
@unteem made it \o/
