### ISSUE TITLE
Add Go Git :)

### ISSUE THREAD

**Issue by pierreozoux** [libresh/applications#76]
Transferred from: https://github.com/IndiePaaS/IndiePaaS/issues/94

https://github.com/gogits/gogs
##

**Comment by frthjf** [comment]
Maybe it's also worth to consider [gitea](https://github.com/go-gitea/gitea), the community fork of gogs. It comes with an official docker file: https://docs.gitea.io/en-us/install-with-docker/

**Comment by almereyda** [comment]
Second that.
