### ISSUE TITLE
Add Mozilla Sync

### ISSUE THREAD

**Issue by pierreozoux** [libresh/applications#93]
Transferred from: https://github.com/IndiePaaS/IndiePaaS/issues/62
##

**Comment by pierreozoux** [comment]
Could use the owncloud client \o/
https://apps.owncloud.com/content/show.php/Mozilla+Sync?content=161793

**Comment by elimisteve** [comment]
+1; this would be sweet as long as all data is encrypted server-side, which I think it is...
